on:
  push:
    branches:
      - main
name: Test, Build and Release IPA
jobs:
  build:
    name: Build and Release IPA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.2'
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
      - name: Build IPA
        run: flutter build ios --debug --no-codesign
      - name: Install Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
      - name: Accept Xcode license
        run: sudo xcodebuild -license accept
      - name: Install CocoaPods
        run: sudo gem install cocoapods
      - name: Set up iOS simulator
        run: |
          sudo xcrun simctl shutdown all
          sudo xcrun simctl erase all
          sudo xcodebuild -createTestDevice "iPhone 12" -register
          sudo xcodebuild -createTestDevice "iPhone 12 Pro" -register
          sudo xcodebuild -createTestDevice "iPhone 12 Pro Max" -register
      - name: Install iOS dependencies
        run: pod install
      - name: Create a Release IPA
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            app-debug.ipa=build/ios/iphoneos/*.ipa
          token: ${{ secrets.TOKEN }}
          tag: v1.0.0-2023057
          distribution: 'internal'