on:
  push:
    branches:
      - main
name: Test, Build and Release APK
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.2'
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
      - name: Build APK
        run: flutter build apk --debug --split-per-abi
      - name: Install Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
      - name: Accept Xcode license
        run: sudo xcodebuild -license accept
      - name: Install CocoaPods
        run: sudo gem install cocoapods
      - name: Set up iOS simulator
        run: |
            sudo xcodebuild -runFirstLaunch
            sudo xcodebuild -createTestDevice "iPhone 12" -register
            sudo xcodebuild -createTestDevice "iPhone 12 Pro" -register
            sudo xcodebuild -createTestDevice "iPhone 12 Pro Max" -register
      - name: Install iOS dependencies
        run: pod install
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.TOKEN }}
          tag: v1.0.0
          distribution: 'internal' # Giá trị phân phối bạn muốn sử dụng (ví dụ: internal, external)