on:
  push:
    branches:
      - main
name: Test, Build and Release IPA
jobs:
  build:
    name: Build and Release IPA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.2'
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
      - name: Build IPA
        run: flutter build ios --debug --no-codesign
      - name: Create a Release IPA
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            app-debug.ipa=build/ios/iphoneos/*.ipa
          token: ${{ secrets.TOKEN }}
          tag: v1.0.0-20230525
          distribution: 'internal'
