on:
  push:
    branches:
      - main
name: Test, Build and Release APK
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Cập nhật thành phiên bản 3 của actions/checkout
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64 # (tùy chọn) Đảm bảo JAVA_HOME trỏ đúng đường dẫn đến phiên bản Java 17 của bạn
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
      - name: Build APK
        run: flutter build apk --debug --split-per-abi
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-*-debug.apk"
          token: ${{ secrets.TOKEN }}
